package home_work_6.classes;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

public class Names {
    public static String getRandomName() {
        List<String> names = new ArrayList<>(100);
        names.add("Александр");
        names.add("Сергей");
        names.add("Владимир");
        names.add("Елена");
        names.add("Татьяна");
        names.add("Андрей");
        names.add("Алексей");
        names.add("Ольга");
        names.add("Николай");
        names.add("Наталья");
        names.add("Анна");
        names.add("Иван");
        names.add("Дмитрий");
        names.add("Ирина");
        names.add("Мария");
        names.add("Михаил");
        names.add("Светлана");
        names.add("Екатерина");
        names.add("Евгений");
        names.add("Виктор");
        names.add("Анастасия");
        names.add("Юрий");
        names.add("Юлия");
        names.add("Валентина");
        names.add("Галина");
        names.add("Людмила");
        names.add("Василий");
        names.add("Игорь");
        names.add("Анатолий");
        names.add("Надежда");
        names.add("Олег");
        names.add("Марина");
        names.add("Павел");
        names.add("Максим");
        names.add("Александра");
        names.add("Нина");
        names.add("Виталий");
        names.add("Валерий");
        names.add("Виктория");
        names.add("Любовь");
        names.add("Роман");
        names.add("Оксана");
        names.add("Денис");
        names.add("Дарья");
        names.add("Константин");
        names.add("Вячеслав");
        names.add("Вера");
        names.add("Евгения");
        names.add("Петр");
        names.add("Антон");
        names.add("Илья");
        names.add("Владислав");
        names.add("Лариса");
        names.add("Лидия");
        names.add("Ксения");
        names.add("Вадим");
        names.add("Наталия");
        names.add("Никита");
        names.add("Григорий");
        names.add("Геннадий");
        names.add("Тамара");
        names.add("Алина");
        names.add("Леонид");
        names.add("Руслан");
        names.add("Елизавета");
        names.add("Кристина");
        names.add("Борис");
        names.add("Кирилл");
        names.add("Артем");
        names.add("Валерия");
        names.add("Полина");
        names.add("Станислав");
        names.add("Инна");
        names.add("Раиса");
        names.add("Алла");
        names.add("Яна");
        names.add("Антонина");
        names.add("Валентин");
        names.add("Егор");
        names.add("Федор");
        names.add("Артём");
        names.add("Георгий");
        names.add("Зинаида");
        names.add("Алена");
        names.add("Степан");
        names.add("Олеся");
        names.add("Маргарита");
        names.add("Лилия");
        names.add("Диана");
        names.add("Даниил");
        names.add("Эдуард");
        names.add("Евдокия");
        names.add("Зоя");
        names.add("Алёна");
        names.add("Вероника");
        names.add("Пётр");
        names.add("Артур");
        names.add("Софья");
        names.add("Клавдия");
        names.add("София");
        Random random = new Random();
        return names.get(random.nextInt(100));
    }
}
